export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const ADMIN_INFO = "ADMIN_INFO";
export const ADMIN_ACTIVEORDEACTIVE = "ADMIN_ACTIVEORDEACTIVE";
export const ADMIN_GENERATE_VERIFICATION_CODE =
  "ADMIN_GENERATE_VERIFICATION_CODE";
export const ADMIN_USERDETAILS = "ADMIN_USERDETAILS";
//export const ADMIN_CHANGEPASSWORD = "ADMIN_CHANGEPASSWORD";
