export const USER_LOGIN = "USER_LOGIN";
export const USER_INFO = "USER_INFO";
export const USER_SIGNUP = "USER_SIGNUP";
export const USER_ACTIVEORDEACTIVE = "USER_ACTIVEORDEACTIVE";
export const USER_GENERATE_VERIFICATION_CODE =
  "USER_GENERATE_VERIFICATION_CODE";
export const USER_USERDETAILS = "USER_USERDETAILS";